application_id: "1354631077045473324"

# Activity type: 0 = Playing, 2 = Listening, 3 = Watching
type: 0

name: "PlayStation 5"
details: "Ea Sports FC 26"
state: "Manager Career"

# Images
largeImageKey: "https://cdn.discordapp.com/attachments/1430509792497242232/1430682908766502932/elden-ring_tf87.1200.jpg?ex=68faaaca&is=68f9594a&hm=94dd18ef943598d58121e64d92c5356a41b5afd38e983b0bea6c42966e7c3e30&"
largeImageText: "Ea Sports FC 26"
smallImageKey: "https://cdn.discordapp.com/attachments/1430509792497242232/1430682912864473278/Dwew7IIW0AAPtTv.jpg?ex=68faaacb&is=68f9594b&hm=20e84eb37da73c4ffd5cf39321fc3e1ca64731ed27ed3ec71bfbe51223d1a706&"
smallImageText: "PlayStation 5"

# URL (optional, works only with certain types)
url: "https://youtube.com/"

# Buttons (optional)
buttons:
  - name: "Youtube"
    url: "https://youtube.com/"
  - name: "Youtube"
    url: "Https://youtube.com/"

# Custom status
custom_status: "Ea FC 26"
custom_emoji: "🔥"
